variable "user" {}
variable "password" {}
variable "vsphere_server" {}
variable "vsphere_host" {}
variable "datacenter" {}
variable "datastore" {}
variable "resource_pool" {}
variable "outside_network" {}
variable "inside_network" {}
variable "publicdefaultgateway" {}
variable "dnsservers" {}
variable "cpus" {}
variable "memory" {}
variable "xcsovapath" {}

variable "certifiedhardware" {}
variable "publicinterfaceaddress" {}
variable "publicdefaultroute" {}
variable "sitelatitude" {}
variable "sitelongitude" {}
variable "nodenames" {}
variable "clustername" {}
variable "sitetoken" {}
variable "guest_type" {}
